---
compiler: "g++"
compiler_options: "-std=c++11 -O3"

paths:
    exe_root: /home/tcomi/projects/IBDmix/exe/{exe}
    source_root: /home/tcomi/projects/IBDmix/IBDmix/
    modern_vcf: "/tigress/AKEY/akey_vol2/wqfu/nobackup/1KGP/\
                 ALL.chr{chrom}.phase3_shapeit2_mvncall_integrated_v5a\
                 .20130502.genotypes.vcf.gz"
    archaic_vcf: /tigress/limingli/data/old-Altai/gz/chr{chrom}.vcf.gz
    # if removed will use all samples
    sample_file: "/projects/AKEY/akey_vol1/home/luchenuw/IBDmix/\
                  sample_file_backup/{population}.txt"
    # if removed will use all positions
    mask_file: "/tigress/AKEY/akey_vol1/home/luchenuw/data/FilterBed/\
                FullVersionforAltai2013_1KGP3strict/\
                Altai2013_1KGP3strict.mask.chr{chrom}.bed"
    genetic_map: "/tigress/tcomi/hg19/{population}/\
                  {population}_recombination_map_hapmap_format_hg19_chr_{chrom}.txt"

    output_root: /tigress/tcomi/ibdmix_temp_with_dists
    sample_name: altai_1kg
    genotype_file: "{output_root}/genotype/{sample_name}_{chrom}.gz"
    ibd_output: "{output_root}/ibd_raw/\
                 {sample_name}_{population}_{chrom}.gz"
    ibd_bed: "{output_root}/ibd_bed/\
              {sample_name}_{population}_{chrom}.gz"
    ibd_bed_gen_dist: "{output_root}/ibd_bed_gen_dist/\
                       {sample_name}_{population}_{chrom}.gz"
    ibd_summary: "{output_root}/ibd_summary/\
                  {sample_name}_{population}_{chrom}_{LOD}_{length}.gz"
    combined_summary: "{output_root}/ibd_summary_combined/\
                       {sample_name}_{chrom}_{LOD}_{length}.txt"

IBDmix:
    # can also include name of archaic, more-stats or inclusive-end
    options: >
        --LOD-threshold 3.0
        --minor-allele-count-threshold 1
        --archaic-error 0.01
        --modern-error-max 0.002
        --modern-error-proportion 2
        #--more-stats
        #--inclusive-end

    # True to calculate total masked bases and largest masked region
    mask_stats: True

    # remove for no summary, add 0s for no filtering
    summary_lod:
        - 4

    summary_length:
        - 30000
        - 50000
        - 100000

#   -g, --genotype:   input genotype file for one chromosome
#                       REQUIRED
#   -o, --output:     output file
#                       REQUIRED
#   -s, --sample:     sample file, one sample name per line
#                       DEFAULT: use all samples
#   -n, --archaic:    name of archaic sample
#                       DEFAULT: first sample taken as archaic
#   -r, --mask:       mask file, sorted, merged bed file
#                       DEFAULT: use all positions
#   -d, --LOD-threshold:
#                     threshold of log(odds) to emit into
#                     output file
#                       DEFAULT: 3.0
#   -m, --minor-allele-count-threshold:
#                     threshold for filtering minor alleles
#                       DEFAULT: 1
#   -a, --archaic-error:
#                     allele error rate for archaic DNA
#                       DEFAULT: 0.01
#   -e, --modern-error-max
#                     maximum allele error rate for modern humans
#                       DEFAULT: 0.0025
#   -c, --modern-error-proportion
#                     ratio between allele error rate and minor
#                     allele frequency for modern humans
#                       DEFAULT: 2
#   -i, --inclusive-end
#                     switch to report the end position as the
#                     first position of decreasing LOD score.
#                       DEFAULT: end is *next* position in genotype file
#   -t, --more-stats
#                     report additional columns detailing execution
#                     sites: total number of sites in genotype file in region
#                     mask and maf: sites which are both in the masked region
#                        and fail MAF cutoff
#                     in_mask: sites in the mask but pass MAF
#                     maf_low: sites failing MAF with low frequency
#                     maf_high: sites failing MAF with high frequency
#                     rec_2_0: sites failing mask or MAF but still considered
#                       due to a genotype of 2 in archaic and 0 in modern
#                     rec_0_2: same as rec_2_0 but with 0 in archaic and
#                        2 in modern
#                       DEFAULT: off
